###
GET http://localhost:8080/areas
###
GET http://localhost:8080/areas/2
###
GET http://localhost:8080/areas/?name=n
###
POST http://localhost:8080/areas
Content-Type: application/json

{
  "areaName": "bardzoNOWA33"
}

###
PATCH http://localhost:8080/areas/update/3
Content-Type: application/json

{
  "areaName": "kotłownia22"
}

###
DELETE http://localhost:8080/areas/3
