###
GET http://localhost:8080/areas
###
GET http://localhost:8080/areas/6
###
GET http://localhost:8080/areas/?name=n
###
POST http://localhost:8080/areas
Content-Type: application/json

{
  "areaName": "bardzoNOWA33"
}

###
PATCH http://localhost:8080/areas/35
Content-Type: application/json

{
  "areaName": "kotłownia2"
}

###
DELETE http://localhost:8080/areas/38
