

###
###
GET http://localhost:8080/faults/

###
GET http://localhost:8080/faults/2

###
GET http://localhost:8080/faults?descr=E

###
GET http://localhost:8080/faults?stat=nie

###
POST http://localhost:8080/faults
Content-Type: application/json

{
  "faultDescribe": "NOWA41",
  "areaId": "2",
  "whoNotifyId": "2"
}

###
PATCH http://localhost:8080/faults/update/3
Content-Type: application/json

{
  "faultDescribe": "wyłączony",
  "specialistId": "4",
  "whoAssignedId": "3",
  "status": "ASSIGNED"
}

###assign
PATCH http://localhost:8080/faults/assign/2
Content-Type: application/json

{
  "specialistId": "4",
  "whoAssignedId": "3"
}

###END
PATCH http://localhost:8080/faults/end/5

###
DELETE http://localhost:8080/faults/2