###
GET http://localhost:8080/faults/

###
GET http://localhost:8080/faults/2

###
GET http://localhost:8080/faults?descr=E

###
GET http://localhost:8080/faults?stat=nie

###
POST http://localhost:8080/faults
Content-Type: application/json

{
  "faultDescribe": "NOWA37",
  "area": {
    "id": "150"
  },
  "whoNotify": {
    "id": "154"
  }
}

###
PATCH http://localhost:8080/faults/156
Content-Type: application/json

{
  "faultDescribe": "wyłączony",
  "status": "ASSIGNED"
}

###
DELETE http://localhost:8080/faults/422