###
POST http://localhost:8080/users
Content-Type: application/json

{
   "password": "123",
   "firstName": "Andy",
   "lastName": "Gor",
   "phone": "12345",
   "emailUserName": "agor@2.pl",
   "role": "ROLE_ADMIN"
}

