###addUser
POST http://localhost:8080/users
Content-Type: application/json

{
   "password": "123",
   "firstName": "Andy",
   "lastName": "Gor",
   "phone": "12345",
   "emailUserName": "agor332@2.pl",
   "role": "ROLE_ASSIGN"
}


###regNewNotifier
POST http://localhost:8080/users/notifier
Content-Type: application/json

{
   "password": "123",
   "firstName": "Andy",
   "lastName": "Notif",
   "phone": "12345",
   "emailUserName": "notif3@2.pl"
}

###findAllSpecialists
GET http://localhost:8080/users/spec

###All
GET http://localhost:8080/users

###MyAccount
GET http://localhost:8080/users/account

###
PATCH http://localhost:8080/users/update/1
Content-Type: application/json

{
  "password": "123",
  "firstName": "Andy",
  "lastName": "Notif",
  "phone": "123456",
  "role": "ROLE_NOTIFIER"
}
